Update bin/vdtg-rmm and vdtg-rmm.config.example
- Improved script logic in bin/vdtg-rmm
- Updated configuration example for clarity and new options

diff --git a/bin/vdtg-rmm b/bin/vdtg-rmm
--- a/bin/vdtg-rmm
+++ b/bin/vdtg-rmm
@@ -16,6 +16,31 @@ if [ -d "/opt/vdtg-rmm" ]; then
         chmod +x /opt/vdtg-rmm/vdtg-rmm-daemon
     fi
 
+    # Check if config file exists, if not copy example config file. If config file exists check for empty values and fill them with default values from example config file, also check for missing lines (including comments) and add them to config file
+    if [ ! -f /opt/vdtg-rmm/vdtg-rmm.config ]; then
+        cp /opt/vdtg-rmm/vdtg-rmm.config.example /opt/vdtg-rmm/vdtg-rmm.config
+    else
+        # Check for empty values and fill them with default values from example config file
+        while IFS= read -r line; do
+            if [[ ! $line == \#* ]] && [ ! -z "$line" ]; then
+                key=$(echo $line | awk -F'=' '{print $1}')
+                value=$(echo $line | awk -F'=' '{print $2}')
+                if [ -z "$value" ]; then
+                    default_value=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config.example | grep -i "^$key=" | awk -F'=' '{print $2}')
+                    sed -i "s/^$key=/$key=$default_value/" /opt/vdtg-rmm/vdtg-rmm.config
+                fi
+            fi
+        done < /opt/vdtg-rmm/vdtg-rmm.config
+
+        # Check for missing lines (including comments) and add them to config file
+        while IFS= read -r line; do
+            if ! grep -Fxq "$line" /opt/vdtg-rmm/vdtg-rmm.config; then
+                echo "$line" >> /opt/vdtg-rmm/vdtg-rmm.config
+            fi
+        done < /opt/vdtg-rmm/vdtg-rmm.config.example
+    fi
+
+    # Check config for cron_enable setting, if true enable cron and add vdtg-rmm-daemon to crontab if not already present (every 6 hours), if false remove vdtg-rmm-daemon from crontab if present
     cron_enable=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config | grep -i 'cron_enable' | awk -F'=' '{print $2}')
     if [ "$cron_enable" == "true" ]; then
         # Ensure cron is installed and enabled
@@ -35,35 +60,11 @@ if [ -d "/opt/vdtg-rmm" ]; then
         fi
     fi
 
-    # Config file logic
-    if [ ! -f /opt/vdtg-rmm/vdtg-rmm.config ]; then
-        cp /opt/vdtg-rmm/vdtg-rmm.config.example /opt/vdtg-rmm/vdtg-rmm.config
-    else
-        # Vul lege values aan
-        while IFS= read -r line; do
-            if [[ ! $line == \#* ]] && [ ! -z "$line" ]; then
-                key=$(echo $line | awk -F'=' '{print $1}')
-                value=$(echo $line | awk -F'=' '{print $2}')
-                if [ -z "$value" ]; then
-                    default_value=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config.example | grep -i "^$key=" | awk -F'=' '{print $2}')
-                    sed -i "s/^$key=/$key=$default_value/" /opt/vdtg-rmm/vdtg-rmm.config
-                fi
-            fi
-        done < /opt/vdtg-rmm/vdtg-rmm.config
-
-        # Voeg ontbrekende regels (inclusief comments) toe
-        while IFS= read -r line; do
-            # Check of regel exact voorkomt in config
-            if ! grep -Fxq "$line" /opt/vdtg-rmm/vdtg-rmm.config; then
-                echo "$line" >> /opt/vdtg-rmm/vdtg-rmm.config
-            fi
-        done < /opt/vdtg-rmm/vdtg-rmm.config.example
-    fi
-
-    # Detect OS and version, then select correct sources.list file
+    # Detect OS and version
     OS_ID="$(. /etc/os-release && echo "$ID")"
     OS_VER="$(. /etc/os-release && echo "$VERSION_ID")"
 
+    # Set sources paths based on detected OS and version, currently only supports Ubuntu but can be expanded in the future for other Debian-based distributions
     if [ "$OS_ID" = "ubuntu" ]; then
         # Set sources paths for Ubuntu
         SRC_LIST_FILE="/opt/vdtg-rmm/sources/ubuntu/${OS_VER}/sources.list"
@@ -91,25 +92,27 @@ if [ -d "/opt/vdtg-rmm" ]; then
         fi
     fi
 
-    # Check config for cron_enable and update_auto settings, if cron_enable is true disable cron before updates and re-enable after updates
+    # Check config for cron_enable setting, if true disable cron before updates to prevent conflicts with package manager and re-enable it after updates
     cron_enable=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config | grep -i 'cron_enable' | awk -F'=' '{print $2}')
     if [ "$cron_enable" == "true" ]; then
         sed -i 's/^\([[:space:]]*cron_enable[[:space:]]*=[[:space:]]*\).*/\1false/' /opt/vdtg-rmm/vdtg-rmm.config
     fi
 
-    update_auto=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config | grep -i 'update_auto' | awk -F'=' '{print $2}')
-    if [ "$update_auto" == "true" ]; then
+    # Check config for update_os setting, if true then refresh repositories and update system
+    update_os=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config | grep -i 'update_os' | awk -F'=' '{print $2}')
+    if [ "$update_os" == "true" ]; then
+
+        # Set non-interactive frontend for apt to avoid prompts during updates
+        export DEBIAN_FRONTEND=noninteractive
+
         # Refresh repositories and update system
         apt clean
         apt update
-        apt upgrade -y
+        apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y upgrade
+
     fi
 
-    # After updates, re-enable cron if it was enabled before
-    if [ "$cron_enable" == "true" ]; then
-        sed -i 's/^\([[:space:]]*cron_enable[[:space:]]*=[[:space:]]*\).*/\1true/' /opt/vdtg-rmm/vdtg-rmm.config
-    fi
-
+    # Check config for install_git setting, if true then check if git is installed and install it if not
     install_git=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config | grep -i 'install_git' | awk -F'=' '{print $2}')
     if [ "$install_git" == "true" ]; then
         if ! dpkg -l | grep -q git; then
@@ -117,6 +120,7 @@ if [ -d "/opt/vdtg-rmm" ]; then
         fi
     fi
 
+    # Check config for install_net_tools setting, if true then check if net-tools is installed and install it if not
     install_net_tools=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config | grep -i 'install_net_tools' | awk -F'=' '{print $2}')
     if [ "$install_net_tools" == "true" ]; then
         if ! dpkg -l | grep -q net-tools; then
@@ -124,6 +128,7 @@ if [ -d "/opt/vdtg-rmm" ]; then
         fi
     fi
 
+    # Check config for install_iputils_ping setting, if true then check if iputils-ping is installed and install it if not
     install_iputils_ping=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config | grep -i 'install_iputils_ping' | awk -F'=' '{print $2}')
     if [ "$install_iputils_ping" == "true" ]; then
         if ! dpkg -l | grep -q iputils-ping; then
@@ -131,7 +136,7 @@ if [ -d "/opt/vdtg-rmm" ]; then
         fi
     fi
 
-    # Locale setup
+    # Check config for locale setting, if set to nl then install locales package if not installed and set system locale to nl_NL.UTF-8
     locale=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config | grep -i 'locale' | awk -F'=' '{print $2}')
     if [ -n "$locale" ]; then
         if ! dpkg -l | grep -q "locales"; then
@@ -140,6 +145,21 @@ if [ -d "/opt/vdtg-rmm" ]; then
         if [ "$locale" == "nl" ]; then
             update-locale LANG=nl_NL.UTF-8 LC_MESSAGES=POSIX
         fi
+    fi
+
+    # Re-enable cron if it was enabled before updates
+    if [ "$cron_enable" == "true" ]; then
+        sed -i 's/^\([[:space:]]*cron_enable[[:space:]]*=[[:space:]]*\).*/\1true/' /opt/vdtg-rmm/vdtg-rmm.config
+    fi
+
+    # Check config for update_reboot setting, if true and /var/run/reboot-required file exists then reboot system
+    update_reboot=$(grep -v '^#' /opt/vdtg-rmm/vdtg-rmm.config | grep -i 'update_reboot' | awk -F'=' '{print $2}')
+    if [ "$update_reboot" == "true" ] && [ -f /var/run/reboot-required ]; then
+        echo "Reboot required. Rebooting now..."
+        reboot
+    else
+        echo "No reboot required. Exiting application."
+        exit
     fi
 
 else
